### ISSUE TITLE
How to integrate custom map?

### ISSUE THREAD

**Issue by windlov2** [gogamid/mapbox-automotive-integration#1]
Hello @gogamid.
I am developing POI App at Pixel AAOS Ref. phone that is without GAS as you know.
So, I'm looking for how to display a map when my POI app uses a PlaceListMapTemplate.
How to display the custom map at your test app?
Do you customize or integrate your own AOSP Host App? then how?

I wait your any feedback for me. Thanks

**Comment by gogamid** [comment]
Hello @windlov2,
I answered to your question here https://github.com/johan12345/EVMap/issues/39
